name: Lint, test and build
on:
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prettify Code
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write **/*.{js,md}
      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Lint, test and Build
        uses: MansaGroup/nrwl-nx-action@v2.0.4
        with:
          targets: lint,test,build
          all: 'true'
